# Generated by Django 4.2.7 on 2026-05-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
